# Generated by Django 5.2.7 on 2025-10-24 01:40

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('ano_ingresso', models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2025)])),
            ],
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('servidor_ifpr', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('modalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('turno', models.CharField(max_length=50)),
                ('duracao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('carga_horaria', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(5000)])),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('avaliador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pfi.avaliador')),
                ('formacao', models.CharField(blank=True, max_length=150, null=True)),
                ('area_tecnica', models.BooleanField(default=False)),
                ('cursos', models.ManyToManyField(to='pfi.curso')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('pfi.avaliador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho_Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('resumo', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=150, null=True)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2025)])),
                ('url', models.URLField(max_length=250)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pfi.aluno')),
                ('coorientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Coorientador', to='pfi.docente')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pfi.docente')),
            ],
            options={
                'verbose_name': 'Projeto Final Interdisciplinar (PFI)',
                'verbose_name_plural': 'Projetos Finais Interdisciplinares',
            },
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apresentacao', models.DateTimeField()),
                ('conceito_final', models.CharField(blank=True, max_length=1, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField()),
                ('membro_banca1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='membro_banca1', to='pfi.avaliador')),
                ('membro_banca2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='membro_banca2', to='pfi.avaliador')),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pfi.trabalho_final')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2025)])),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pfi.curso')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pfi.turma'),
        ),
    ]
