# Generated by Django 5.2.7 on 2025-10-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliador',
            name='ativo',
        ),
        migrations.AlterField(
            model_name='avaliador',
            name='servidor_ifpr',
            field=models.BooleanField(default=True, help_text='Marque essa opção caso seja Servidor do IFPR', verbose_name='Servidor do IFPR'),
        ),
        migrations.AlterField(
            model_name='avaliador',
            name='telefone',
            field=models.CharField(blank=True, help_text='Informe um telefone ou celular para contato', max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
