# Generated by Django 5.2.7 on 2025-10-25 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfi', '0002_remove_avaliador_ativo_alter_avaliador_servidor_ifpr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banca',
            name='status',
            field=models.CharField(blank=True, default='PENDENTE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho_final',
            name='coorientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Coorientador', to='pfi.avaliador'),
        ),
        migrations.AlterField(
            model_name='trabalho_final',
            name='url',
            field=models.URLField(max_length=250, verbose_name='URL'),
        ),
    ]
