# Generated by Django 5.2.7 on 2025-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfi', '0003_alter_banca_status_alter_trabalho_final_coorientador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nome_curso_abreviado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banca',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
